# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-03 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=200)),
                ('Ingredientes', models.TextField()),
                ('Preparacion', models.TextField()),
                ('Fecha_publicacion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
